#!/bin/bash

...

# Cancun Project, Module Mode, Production
if [ "$1" = "P1" ] ; then cd "$CUSTOM"/cancun; python cancun.py -m identification ; exit 1 ; fi
if [ "$1" = "P2" ] ; then cd "$CUSTOM"/cancun; python cancun.py -m hour ; exit 1 ; fi
if [ "$1" = "P3" ] ; then cd "$CUSTOM"/cancun; python cancun.py -m date ; exit 1 ; fi
if [ "$1" = "P4" ] ; then cd "$CUSTOM"/cancun; python cancun.py -m weather ; exit 1 ; fi
if [ "$1" = "P5" ] ; then cd "$CUSTOM"/cancun; python cancun.py -m temperature ; exit 1 ; fi

# Cancun Project, Module Mode, Experimental
if [[ "$1" == PS* ]] ; then cd "$CUSTOM"/cancun; python cancun.py -d $1 ; exit 1 ; fi
if [[ "$1" == SS* ]] ; then cd "$CUSTOM"/cancun; python cancun.py -d $1 ; exit 1 ; fi
if [[ "$1" == A* ]] ; then cd "$CUSTOM"/cancun; python cancun.py -d $1 ; exit 1 ; fi

exit 0
