#!/bin/bash

# This is the custom decode file. Make sure all valid codes exit with 
# "exit 1". To enable the codes below, the "#" must be removed from the 
# start. This would allow the node to be disabled with the code 12001 
# This would allow the node to be enabled with the code 12002

#if [ "$1" = "12001" ] ; then "$SCRIPT"/disable ; exit 1 ; fi
#if [ "$1" = "12002" ] ; then "$SCRIPT"/enable ; exit 1 ; fi

# Cancun Project, Scheduler Mode
if [ "$1" = "S00" ] ; then cd "$CUSTOM"/cancun; python cancun.py -s stop ; exit 1 ; fi
if [ "$1" = "S01" ] ; then cd "$CUSTOM"/cancun; python cancun.py -s start ; exit 1 ; fi

# Cancun Project, Random Mode
if [ "$1" = "P00" ] ; then cd "$CUSTOM"/cancun; python cancun.py -r stop ; exit 1 ; fi
if [ "$1" = "P01" ] ; then cd "$CUSTOM"/cancun; python cancun.py -r start ; exit 1 ; fi

# Cancun Project, Module Mode, General
if [ "$1" = "P1" ] ; then cd "$CUSTOM"/cancun; python cancun.py -m identification ; exit 1 ; fi
if [ "$1" = "P2" ] ; then cd "$CUSTOM"/cancun; python cancun.py -m hour ; exit 1 ; fi
if [ "$1" = "P3" ] ; then cd "$CUSTOM"/cancun; python cancun.py -m date ; exit 1 ; fi
if [ "$1" = "P4" ] ; then cd "$CUSTOM"/cancun; python cancun.py -m weather ; exit 1 ; fi
if [ "$1" = "P5" ] ; then cd "$CUSTOM"/cancun; python cancun.py -m seismology ; exit 1 ; fi
if [ "$1" = "P6" ] ; then cd "$CUSTOM"/cancun; python cancun.py -m stations ; exit 1 ; fi

# Cancun Project, Module Mode, Learning
if [ "$1" = "P10" ] ; then cd "$CUSTOM"/cancun; python cancun.py -m morselearn ; exit 1 ; fi
if [ "$1" = "P11" ] ; then cd "$CUSTOM"/cancun; python cancun.py -m morsecontest ; exit 1 ; fi
if [ "$1" = "P12" ] ; then cd "$CUSTOM"/cancun; python cancun.py -m regulations ; exit 1 ; fi

# Cancun Project, Module Mode, Experimental
if [ "$1" = "P90" ] ; then cd "$CUSTOM"/cancun; python cancun.py -m command ; exit 1 ; fi
if [ "$1" = "P91" ] ; then cd "$CUSTOM"/cancun; python cancun.py -m assistant ; exit 1 ; fi
if [ "$1" = "P92" ] ; then cd "$CUSTOM"/cancun; python cancun.py -m wolfram ; exit 1 ; fi
if [ "$1" = "P93" ] ; then cd "$CUSTOM"/cancun; python cancun.py -m news ; exit 1 ; fi
if [ "$1" = "P94" ] ; then cd "$CUSTOM"/cancun; python cancun.py -m vm -d $1; exit 1 ; fi
if [ "$1" = "P95" ] ; then cd "$CUSTOM"/cancun; python cancun.py -w start; exit 1 ; fi

cd "$CUSTOM"/cancun; python cancun.py -d $1;

exit 0
